### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by Eidorian** [ikkentim/SampSharp#333]
Hi,

This exception is thrown when this line (below) is called. It occurs when a button is clicked.

`var response = await _dialogService.Show(player.Entity, dialog);`

StackTrace :
```
> at SampSharp.Entities.EntityManager.ComponentStore.GetAll[T]()
at SampSharp.Entities.EntityManager.GetComponents[T](EntityId entity)
at SampSharp.Entities.EntityManager.Destroy[T](EntityId entity)
at SampSharp.Entities.SAMP.DialogService.Show[TResponse](EntityId player, IDialog`1 dialog, Action`1 responseHandler)
at SampSharp.Entities.SAMP.DialogService.Show[TResponse](EntityId player, IDialog`1 dialog)
at Polaris.Server.Services.Dialogs.DialogSigninService.<ShowMail>d__13.MoveNext()`
```
Source : **SampSharp.Entities**

Detailed code link : https://pastebin.com/AD8D58bU

**Comment by nathan130200** [comment]
Just a tip, don't use `async` keyword with `void` return type, in your case return Task<TResult> and [TaskCompletionSource<TResult>](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1?view=netcore-3.1)
