### ISSUE TITLE
[ECS] error OnPlayerTakeDamage and OnPlayerGiveDamage

### ISSUE THREAD

**Issue by A1dyyyy** [ikkentim/SampSharp#350]
[Event]
public void OnPlayerTakeDamage(Player player, Player issuer, float amount, Weapon weapon, BodyPart bodypart)
{
}
and OnPlayerGiveDamage

im get this error:
`[SampSharp:ERROR] Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> SampSharp.Entities.EntityNotFoundException: The specified entity could not be found. (Parameter 'entity')
   at SampSharp.Entities.EntityManager.GetComponent[T](EntityId entity)
   at lambda_method(Closure , Object , Object[] , IServiceProvider , IEntityManager )
   at SampSharp.Entities.EventService.<>c__DisplayClass11_0.<CreateInvoker>b__0(Object instance, EventContext eventContext)
   at SampSharp.Entities.EventService.Invoke(EventContext context)
   at SampSharp.Entities.SAMP.EntityMiddleware.Invoke(EventContext context, IEntityManager entityManager)
   at lambda_method(Closure , Object , EventContext , IServiceProvider )
   at SampSharp.Entities.EcsBuilderUseMiddlewareExtensions.<>c__DisplayClass3_1.<UseMiddleware>b__2(EventContext context)
   at SampSharp.Entities.SAMP.EntityMiddleware.Invoke(EventContext context, IEntityManager entityManager)
   at lambda_method(Closure , Object , EventContext , IServiceProvider )
   at SampSharp.Entities.EcsBuilderUseMiddlewareExtensions.<>c__DisplayClass3_1.<UseMiddleware>b__2(EventContext context)
   at SampSharp.Entities.EventService.<>c__DisplayClass12_0.<BuildInvoke>b__0(Object[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SampSharp.Core.Callbacks.Callback.Invoke(Byte[] buffer, Int32 startIndex)
   at SampSharp.Core.HostedGameModeClient.PublicCall(String name, IntPtr data, Int32 length)
[SampSharp:ERROR] Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> SampSharp.Entities.EntityNotFoundException: The specified entity could not be found. (Parameter 'entity')
   at SampSharp.Entities.EntityManager.GetComponent[T](EntityId entity)
   at lambda_method(Closure , Object , Object[] , IServiceProvider , IEntityManager )
   at SampSharp.Entities.EventService.<>c__DisplayClass11_0.<CreateInvoker>b__0(Object instance, EventContext eventContext)
   at SampSharp.Entities.EventService.Invoke(EventContext context)
   at SampSharp.Entities.SAMP.EntityMiddleware.Invoke(EventContext context, IEntityManager entityManager)
   at lambda_method(Closure , Object , EventContext , IServiceProvider )
   at SampSharp.Entities.EcsBuilderUseMiddlewareExtensions.<>c__DisplayClass3_1.<UseMiddleware>b__2(EventContext context)
   at SampSharp.Entities.SAMP.EntityMiddleware.Invoke(EventContext context, IEntityManager entityManager)
   at lambda_method(Closure , Object , EventContext , IServiceProvider )
   at SampSharp.Entities.EcsBuilderUseMiddlewareExtensions.<>c__DisplayClass3_1.<UseMiddleware>b__2(EventContext context)
   at SampSharp.Entities.EventService.<>c__DisplayClass12_0.<BuildInvoke>b__0(Object[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SampSharp.Core.Callbacks.Callback.Invoke(Byte[] buffer, Int32 startIndex)
   at SampSharp.Core.HostedGameModeClient.PublicCall(String name, IntPtr data, Int32 length)`

**Comment by ikkentim** [comment]
closed in 0b6b2e5
